version: "2"
services:
  registry:
    image: joxit/docker-registry-ui:static
    expose:
      - 80
    networks:
      - default
      - reverse-proxy
    env_file:
      - .env
    restart: always
networks:
  reverse-proxy:
    external:
      name: reverse-proxy

