version: "2"
services:
  registry-ui:
    image: joxit/docker-registry-ui:static
    expose:
      - 80
    networks:
      - default
      - reverse-proxy
    depends_on:
      - registry
    env_file:
      - .env.ui
    restart: always
  registry:
    image: registry:2
    expose:
      - 5000
    networks:
      - default
    env_file:
      - .env
    volumes:
      - ./registry:/var/lib/registry
    restart: always
networks:
  reverse-proxy:
    external:
      name: reverse-proxy

